spring:
  application:
    name: payment-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8084

stripe:
  secret-key: ${STRIPE_SECRET_KEY}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: production

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/