server:
  port: 9000

spring:
  application:
    name: evently-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: events-service
              uri: lb://events-service
              predicates:
                - Path=/events/**,/venues/**,/performers/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true