server:
  port: 9000

spring:
  application:
    name: evently-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: events-service
              uri: http://localhost:8082
              predicates:
                - Path=/events/**,/locations/**,/artists/**,/categories/**,/admin/**
            - id: booking-service
              uri: http://localhost:8081
              predicates:
                - Path=/tickets/**,/orders/**
            - id: user-service
              uri: http://localhost:8085
              predicates:
                - Path=/user/**,/auth/**,/follows/**
            - id: notification-service
              uri: http://localhost:8083
              predicates:
                - Path=/notifications/**
            - id: payment-service
              uri: http://localhost:8084
              predicates:
                - Path=/payments/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    io.jsonwebtoken: DEBUG
#    # Replace 'package.jwt' with the actual package name of your JWTUtility
#    package.jwt: DEBUG