server:
  port: 9000

spring:
  application:
    name: evently-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/auth/**,/user/**,/follows/**,/admin/users/**

            - id: events-service
              uri: lb://events-service
              predicates:
                - Path=/events/**,/locations/**,/artists/**,/categories/**,/admin/events/**,/admin/locations/**,/admin/artists/**,/admin/categories/**

            - id: booking-service
              uri: lb://booking-service
              predicates:
                - Path=/tickets/**,/orders/**,/refunds/**,/promo-codes/**,/admin/orders/**,/admin/promo-codes/**

            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/payment-transactions/**,/admin/payment-transactions/**

            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/notifications/**,/admin/notifications/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:  http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    io.jsonwebtoken: DEBUG