server:
  port: 8085

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://postegress:5432/users_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  sql:
    init:
      mode: always
