services:
  postgres:
    image: postgres:latest
    container_name: evently-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminPassword
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#    networks:
#      - evently-network

  #  eureka:
  #    image: eureka
  #    container_name: eureka-service
  #    ports:
  #      - "8761:8761"
  #    networks:
  #      - evently-network

  # --- KAFKA & CONDUKTOR ---
  kafka:
    image: apache/kafka:latest
    container_name: evently-message-broker
    ports:
      - "9092:9092"
#  conduktor-console:
#    image: conduktor/conduktor-console:latest
#    container_name: conduktor-console
#    ports:
#      - "8081:8080" # Changed host port to 8081 because pgAdmin is using 8080
#    environment:
#      - CDK_DATABASE_URL=postgresql://conduktor:conduktor@postgres-conductor:5432/conduktor
#      - CDK_DATABASE_PASSWORD=conduktor
#      - KAFKA_BOOTSTRAP_SERVERS=message-broker:9092
#      - CDK_ADMIN_EMAIL=admin@evently.com
#      - CDK_ADMIN_PASSWORD=AdminPassword123!
#    depends_on:
#      - postgres-conductor
#      - kafka
#    networks:
#      - evently-network

#  postgres-conductor:
#    image: postgres:14
#    container_name: postgres-conductor
#    environment:
#      - POSTGRES_DB=conduktor
#      - POSTGRES_USER=conduktor
#      - POSTGRES_PASSWORD=conduktor
#    networks:
#      - evently-network

  # --- OTHER SERVICES ---
  pgadmin:
    image: dpage/pgadmin4
    container_name: postgres-UI
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminPassword
    ports:
      - "7654:80"
#    networks:
#      - evently-network

  redis:
    image: redis:latest
    container_name: ticket-service-redis
    volumes:
      - ./users.acl:/etc/redis/users.acl
    command: ["redis-server", "--aclfile", "/etc/redis/users.acl"]
    ports:
      - "6379:6379"
#    networks:
#      - evently-network

  redis-insight:
    image: redis/redisinsight:latest
    container_name: ticket-service-redis-insight
    ports:
      - "5540:5540"
    depends_on:
      - redis
#    networks:
#      - evently-network
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "9876:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: message-broker:9092
      DYNAMIC_CONFIG_ENABLED: 'true'
#    networks:
#      - evently-network

#networks:
#  evently-network:
#    driver: bridge