services:
  postgres:
    image: postgres
    container_name: ticket-service-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - ticket-network

  redis:
    image: redis
    container_name: ticket-service-redis
    command: [ "redis-server", "--user", "${REDIS_USER}", "on", ">${REDIS_PASSWORD}", "~*", "+@all", "--user", "default", "off" ]
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - ticket-network

  redis-insight:
    image: redis/redisinsight
    container_name: ticket-service-redis-insight
    ports:
      - "5540:5540"
    depends_on:
      - redis
    networks:
      - ticket-network

networks:
  ticket-network:
    driver: bridge