spring:
  application:
    name: booking-service
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: booking-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "events.event,events.user,events.order,events.promoCode"
  datasource:
    url: jdbc:postgresql://postgres:5432/booking_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8081

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.jdbc: DEBUG
    org.springframework.orm: DEBUG
    org.springframework.data: DEBUG
    org.hibernate: DEBUG