aws:
  accessKeyId: ${AWS_ACCESS_KEY}
  secretAccessKey: ${AWS_SECRET_KEY}
  region: eu-north-1
  s3:
    bucketName: evently-spring

spring:
  application:
    name: events-service
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 50
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: events-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "events.ticket,events.user"
  datasource:
    url: jdbc:postgresql://postgres:5432/events_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  data:
    redis:
      host: redis
      port: 6379
      username: admin
      password: password123


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8082

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.jdbc: DEBUG
    org.springframework.orm: DEBUG
    org.springframework.data: DEBUG
    org.hibernate: DEBUG