spring:
  application:
    name: notification-service

  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "events.user,events.ticket,events.event"

  datasource:
    url: jdbc:postgresql://localhost:5432/notifications_db
    username: admin
    password: adminPassword

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

server:
  port: 8083
kafka:
  bootstrap-servers: localhost:9092
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true