name: Lint Code Base

on:
  push:
    branches: [ '**' ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Validate YAML files
      uses: actions/validate-yaml-action@v1
      with:
        files: '**/*.yml'
